linter:
  rules:
    prefer_relative_imports: false
    prefer_double_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

  plugins:
    - custom_lint
