linter:
  rules:
    require_trailing_commas: true
    prefer_relative_imports: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

  plugins:
    - custom_lint
