linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_relative_imports: false
    sort_constructors_first: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/l10n/gen/**"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"
    - "**/*.fields.dart"

  errors:
    invalid_annotation_target: ignore
