targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false

global_options:
  freezed:freezed:
    runs_before:
      - fields_generator:fields_generator
