global_options:
  freezed:freezed:
    runs_before:
      - fields_generator:fields_generator
  fields_generator:fields_generator:
    runs_before:
      - json_serializable:json_serializable
      
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false