name: quran_api
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.2.3

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  change_case: ^2.0.1
  retrofit_generator: ">=7.0.0 <8.0.0"
