name: quran_api
description: Implementation of the Quran API based on the official documentation
version: 0.1.1
homepage: https://github.com/the-key-software/quran_api

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  faker: ^2.2.0
  swagger_parser: ^1.20.1

dev_dependencies:
  test: ^1.25.9
  lints: ^5.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  swagger_to_dart: 0.1.1
