name: quran_api
description: Implementation of the Quran API based on the official documentation
version: 0.0.8
homepage: https://github.com/the-key-software/quran_api

environment:
  sdk: ^3.2.3

dependencies:
  dio: ^5.4.0
  retrofit: ">=4.0.0 <5.0.0"
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fields_generator: 
    path: ../fields_generator/fields_generator

dev_dependencies:
  build_runner: ^2.4.8

  test: ^1.24.0

  lints: ^2.1.0

  freezed: ^2.4.6
  json_serializable: ^6.7.1

  change_case: ^2.0.1

  retrofit_generator: ">=7.0.0 <8.0.0"
  http_mock_adapter: ^0.6.1
