swagger_to_dart:
  # You must provide the file path and/or url to the OpenApi schema.

  # Sets the OpenApi schema path directory for api definition.
  # schema_path: schemes/openapi.json
  input_directory: schema/swagger.json

  # Optional. Skip parameters with names.
  skipped_parameters:
    - "Accept-Language"
    - "X-Platform"
