// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import

// Clients
export 'clients/audio_client.dart';
export 'clients/chapters_client.dart';
export 'clients/verses_client.dart';
export 'clients/juz_client.dart';
export 'clients/quran_client.dart';
export 'clients/resources_client.dart';
export 'clients/search_client.dart';
// Data classes
export 'models/audiofile.dart';
export 'models/author.dart';
export 'models/chapter_info.dart';
export 'models/language.dart';
export 'models/media_content.dart';
export 'models/recitation.dart';
export 'models/tafsir.dart';
export 'models/translated_name.dart';
export 'models/translation.dart';
export 'models/transliteration.dart';
export 'models/verse.dart';
export 'models/word.dart';
export 'models/chapter.dart';
export 'models/resource.dart';
export 'models/pagination.dart';
export 'models/juz.dart';
export 'models/chapter_recitation.dart';
export 'models/chapter_reciters.dart';
export 'models/get_chapter_recitations_id_chapter_number_response.dart';
export 'models/get_chapter_recitations_id_response.dart';
export 'models/get_chapters_response.dart';
export 'models/get_chapters_id_response.dart';
export 'models/get_chapters_chapter_id_info_response.dart';
export 'models/get_verses_by_chapter_chapter_number_response.dart';
export 'models/get_verses_by_page_page_number_response.dart';
export 'models/get_verses_by_juz_juz_number_response.dart';
export 'models/get_verses_by_hizb_hizb_number_response.dart';
export 'models/get_verses_by_rub_rub_el_hizb_number_response.dart';
export 'models/get_verses_by_key_verse_key_response.dart';
export 'models/get_verses_random_response.dart';
export 'models/verses.dart';
export 'models/get_quran_verses_indopak_response.dart';
export 'models/verses2.dart';
export 'models/get_quran_verses_uthmani_tajweed_response.dart';
export 'models/verses3.dart';
export 'models/get_quran_verses_uthmani_response.dart';
export 'models/verses4.dart';
export 'models/get_quran_verses_uthmani_simple_response.dart';
export 'models/verses5.dart';
export 'models/get_quran_verses_imlaei_response.dart';
export 'models/meta.dart';
export 'models/get_quran_recitations_recitation_id_response.dart';
export 'models/meta2.dart';
export 'models/get_quran_translations_translation_id_response.dart';
export 'models/get_resources_chapter_reciters_response.dart';
export 'models/meta3.dart';
export 'models/get_quran_tafsirs_tafsir_id_response.dart';
export 'models/verses6.dart';
export 'models/get_quran_verses_code_v_response.dart';
export 'models/verses7.dart';
export 'models/get_quran_verses_code_v_response2.dart';
export 'models/get_recitations_recitation_id_by_chapter_chapter_number_response.dart';
export 'models/get_recitations_recitation_id_by_juz_juz_number_response.dart';
export 'models/get_recitations_recitation_id_by_page_page_number_response.dart';
export 'models/get_recitations_recitation_id_by_rub_rub_el_hizb_number_response.dart';
export 'models/get_recitations_recitation_id_by_hizb_hizb_number_response.dart';
export 'models/get_recitations_recitation_id_by_ayah_ayah_key_response.dart';
export 'models/info.dart';
export 'models/get_resources_recitations_recitation_id_info_response.dart';
export 'models/info2.dart';
export 'models/get_resources_translations_translation_id_info_response.dart';
export 'models/get_resources_translations_response.dart';
export 'models/get_resources_tafsirs_response.dart';
export 'models/get_resources_tafsirs_tafsir_id_info_response.dart';
export 'models/get_resources_recitation_styles_response.dart';
export 'models/chapter_infos.dart';
export 'models/get_resources_chapter_infos_response.dart';
export 'models/get_resources_verse_media_response.dart';
export 'models/translated_name2.dart';
export 'models/translated_name3.dart';
export 'models/verse_mapping.dart';
export 'models/words.dart';
// Root client
export 'quran_api_client.dart';

